### ISSUE TITLE
Bower dependency for hotkeys

### ISSUE THREAD

**Issue by chrismichaels84** [steveathon/bootstrap-wysiwyg#16]
Everytime I try to pul in jQuery Hotkeys via bower, I get an error that there is not satisfiable version. I ended up having to define the git endpoint to fix this. It's an upstream problem, but this solves it.

**Comment by chrismichaels84** [comment]
Resolved

**Comment by hpatoio** [comment]
@chrismichaels84 how you solve it ?

**Comment by chrismichaels84** [comment]
You can click on update jquery hotkeys dep #17
<https://github.com/steveathon/bootstrap-wysiwyg/issues/17> above to see
the pull request. From there, click on the two commits to see the exact
changes. It's only a couple lines. I made sure the dependency in the bower
file was pointing to an active fork of jquery.hotkeys and I made sure it
pointed directly to that endpoint, not some alias that leads in circles.

On Mon, Mar 16, 2015 at 12:00 PM, Simone Fumagalli <notifications@github.com

**Comment by hpatoio** [comment]
Great ! I didn't see the PR !

BTW I still get the error where I run `bower install --save bootstrap-wysiwyg-steveathon`

```
bower bootstrap-wysiwyg-steveathon#*           cached git://github.com/steveathon/bootstrap-wysiwyg.git#1.0.2
bower bootstrap-wysiwyg-steveathon#*         validate 1.0.2 against git://github.com/steveathon/bootstrap-wysiwyg.git#*
bower jquery.hotkeys#>= 1.0                not-cached git://github.com/tzuryby/jquery.hotkeys.git#>= 1.0
bower jquery.hotkeys#>= 1.0                   resolve git://github.com/tzuryby/jquery.hotkeys.git#>= 1.0
bower bootstrap#>= 2.0                         cached git://github.com/twbs/bootstrap.git#3.3.4
bower bootstrap#>= 2.0                       validate 3.3.4 against git://github.com/twbs/bootstrap.git#>= 2.0
bower fontawesome#>= 3.0.0                     cached git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower fontawesome#>= 3.0.0                   validate 4.3.0 against git://github.com/FortAwesome/Font-Awesome.git#>= 3.0.0
bower google-code-prettify#>= 1.0.1            cached git://github.com/tcollard/google-code-prettify.git#1.0.4 
bower google-code-prettify#>= 1.0.1          validate 1.0.4 against git://github.com/tcollard/google-code-prettify.git#>= 1.0.1
bower jquery.hotkeys#>= 1.0              ENORESTARGET No tag found that was able to satisfy >= 1.0

Additional error details:
No versions found in git://github.com/tzuryby/jquery.hotkeys.git
```
Did you forget to tag a new release ? I'm installing it with `bower install --save bootstrap-wysiwyg-steveathon#master`

**Comment by chrismichaels84** [comment]
It may be a bower cache problem. Try to run `bower cache clean` and clear out your bower_components directory before trying to reinstall. The first line of that log says its trying to load from a cached version of bootstrap-wysiwyg that is version 1.0.2 which is before the dependency update, so it tries to get jquery.hotkeys from a defunkt fork.

Let me know if this helps.

**Comment by hpatoio** [comment]
I tried already after a `bower cache clean` and didn't work. I've tried again now and this is the output:

```
bower ckeditor#~4.4.7       not-cached git://github.com/ckeditor/ckeditor-releases.git#~4.4.7
bower ckeditor#~4.4.7          resolve git://github.com/ckeditor/ckeditor-releases.git#~4.4.7
bower wysihtml5x#0.4.13     not-cached git://github.com/Edicy/wysihtml5.git#0.4.13
bower wysihtml5x#0.4.13        resolve git://github.com/Edicy/wysihtml5.git#0.4.13
bower bootstrap-wysiwyg-steveathon#*       not-cached git://github.com/steveathon/bootstrap-wysiwyg.git#*
bower bootstrap-wysiwyg-steveathon#*          resolve git://github.com/steveathon/bootstrap-wysiwyg.git#*
bower ckeditor#~4.4.7                        download https://github.com/ckeditor/ckeditor-releases/archive/4.4.7.tar.gz
bower bootstrap-wysiwyg-steveathon#*         download https://github.com/steveathon/bootstrap-wysiwyg/archive/1.0.2.tar.gz
bower wysihtml5x#0.4.13                      download https://github.com/Edicy/wysihtml5/archive/0.4.13.tar.gz
bower bootstrap-wysiwyg-steveathon#*          extract archive.tar.gz
bower bootstrap-wysiwyg-steveathon#*         resolved git://github.com/steveathon/bootstrap-wysiwyg.git#1.0.2
bower jquery.hotkeys#>= 1.0                not-cached git://github.com/tzuryby/jquery.hotkeys.git#>= 1.0
bower jquery.hotkeys#>= 1.0                   resolve git://github.com/tzuryby/jquery.hotkeys.git#>= 1.0
bower ckeditor#~4.4.7                         extract archive.tar.gz
bower ckeditor#~4.4.7                    invalid-meta ckeditor is missing "main" entry in bower.json
bower ckeditor#~4.4.7                    invalid-meta ckeditor is missing "ignore" entry in bower.json
bower ckeditor#~4.4.7                        resolved git://github.com/ckeditor/ckeditor-releases.git#4.4.7
bower wysihtml5x#0.4.13                       extract archive.tar.gz
bower wysihtml5x#0.4.13                      mismatch Version declared in the json (0.4.12) is different than the resolved one (0.4.13)
bower wysihtml5x#0.4.13                      resolved git://github.com/Edicy/wysihtml5.git#0.4.13
bower jquery.hotkeys#>= 1.0              ENORESTARGET No tag found that was able to satisfy >= 1.0

Additional error details:
No versions found in git://github.com/tzuryby/jquery.hotkeys.git
```

but if I run `bower install bootstrap-wysiwyg-steveathon#master` then I get:

```
bower bootstrap-wysiwyg-steveathon#master       not-cached git://github.com/steveathon/bootstrap-wysiwyg.git#master
bower bootstrap-wysiwyg-steveathon#master          resolve git://github.com/steveathon/bootstrap-wysiwyg.git#master
bower ckeditor#~4.4.7                               cached git://github.com/ckeditor/ckeditor-releases.git#4.4.7
bower ckeditor#~4.4.7                             validate 4.4.7 against git://github.com/ckeditor/ckeditor-releases.git#~4.4.7
bower wysihtml5x#0.4.13                             cached git://github.com/Edicy/wysihtml5.git#0.4.13
bower wysihtml5x#0.4.13                           validate 0.4.13 against git://github.com/Edicy/wysihtml5.git#0.4.13
bower bootstrap-wysiwyg-steveathon#master         checkout master
bower bootstrap-wysiwyg-steveathon#master         resolved git://github.com/steveathon/bootstrap-wysiwyg.git#63e2bf6039
bower jquery.hotkeys#master                     not-cached https://github.com/jeresig/jquery.hotkeys.git#master
bower jquery.hotkeys#master                        resolve https://github.com/jeresig/jquery.hotkeys.git#master
bower jquery.hotkeys#master                       checkout master
bower jquery.hotkeys#master                       resolved https://github.com/jeresig/jquery.hotkeys.git#818081bbcb
bower wysihtml5x#0.4.13                            install wysihtml5x#0.4.13
bower ckeditor#~4.4.7                              install ckeditor#4.4.7
bower bootstrap-wysiwyg-steveathon#master          install bootstrap-wysiwyg-steveathon#63e2bf6039
bower jquery.hotkeys#master                        install jquery.hotkeys#818081bbcb

wysihtml5x#0.4.13 ../../../web/supplier/bower/wysihtml5x

ckeditor#4.4.7 ../../../web/supplier/bower/ckeditor

bootstrap-wysiwyg-steveathon#63e2bf6039 ../../../web/supplier/bower/bootstrap-wysiwyg-steveathon
├── bootstrap#3.3.4
├── fontawesome#4.3.0
├── google-code-prettify#1.0.4
├── jquery#2.1.3
└── jquery.hotkeys#818081bbcb

jquery.hotkeys#818081bbcb ../../../web/supplier/bower/jquery.hotkeys
└── jquery#2.1.3
```

**Comment by chrismichaels84** [comment]
Well the second one is what you want, so I guess that's just what you'll have to do to install it through bower until the repository maintainer tags a new release. That is something I cannot do. This isn't my repo. You definitely want to install the master branch.

**Comment by steveathon** [comment]
Fixed - I updated the releases to include the latest.

**Comment by hpatoio** [comment]
:+1: @steveathon ! I was about to ping you !
